[package]
name = "adblock_bridge"
version = "0.1.0"
edition = "2021"

[lib]
name = "adblock_bridge"
crate-type = ["cdylib"]

[dependencies]
adblock = { version = "0.13", default-features = false, features = ["embedded-domain-resolver", "full-regex-handling"] }
jni = "0.21"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
